set encoding=utf-8
set backspace=indent,eol,start "backspace が効かない

if &compatible
  set nocompatible
endif

" Required:
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('~/.cache/dein')
  call dein#begin('~/.cache/dein')

  " Let dein manage dein
  " Required:
  call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')

  call dein#add('Yggdroot/indentLine')
  call dein#add('airblade/vim-gitgutter')
  call dein#add('arcticicestudio/nord-vim')
  call dein#add('ekalinin/Dockerfile.vim')
  call dein#add('elixir-editors/vim-elixir')
  call dein#add('othree/yajs.vim')
  call dein#add('posva/vim-vue')
  call dein#add('rust-lang/rust.vim')
  call dein#add('scrooloose/nerdtree')
  call dein#add('tpope/vim-fugitive')
  call dein#add('tpope/vim-rails')
  call dein#add('tpope/vim-surround')
  call dein#add('vim-airline/vim-airline')
  call dein#add('vim-airline/vim-airline-themes')
  call dein#add('vim-ruby/vim-ruby')

  call dein#add($HOME . '/homebrew/opt/fzf')
  call dein#add('junegunn/fzf.vim')

  " Required:
  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

colorscheme nord

" keybind
" insert mode
imap <C-j> <esc>

" normal mode
nmap nt :NERDTreeToggle

" display
set number
set cursorline
set notitle
set list
set listchars=tab:»-,trail:~

let loaded_matchparen = 1

set clipboard=unnamedplus

" tab
set expandtab
set autoindent
set tabstop=2
set shiftwidth=2

set showmatch
" statusbar
set laststatus=2

" file
set noswapfile
set nobackup

autocmd BufNewFile,BufRead *.php set tabstop=4 shiftwidth=4
autocmd BufNewFile,BufRead *.{md,,markdown} set filetype=markdown
autocmd BufNewFile,BufRead *.hbs set filetype=haml

" airline
let g:airline_theme= 'nord'
let g:airline_powerline_fonts = 1

" indentLine
let g:indentLine_fileTypeExclude = ['help', 'nerdtree']

let g:markdown_fenced_languages = [
\  'coffee',
\  'haml',
\  'javascript',
\  'js=javascript',
\  'ruby',
\]

" QuickFix
autocmd QuickFixCmdPost *grep* cwindow
