export GOPATH=$HOME

case $OSTYPE in
  darwin*)
    setopt no_global_rcs

    export PATH=/usr/local/bin:$PATH:/usr/sbin:/sbin
    export PATH=$HOME/homebrew/bin:$PATH
    export PATH=$PATH:$HOME/homebrew/share/git-core/contrib/diff-highlight
    export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
  ;;
esac

export PATH=$HOME/.nodebrew/current/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$PATH:~/bin
