export GOPATH=$HOME

case $OSTYPE in
  darwin*)
    export ANDROID_HOME=$HOME/Library/Android/sdk

    export PATH=$PYENV_ROOT/bin:$PATH
    export PATH=$HOME/homebrew/bin:$PATH
    export PATH=$PATH:$ANDROID_HOME/platform-tools
  ;;
esac

export PATH=$HOME/.nodebrew/current/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$PATH:~/bin
export PATH=$PATH:/usr/local/bin
