add_newline = false

prompt_order = [
  "kubernetes",
  "directory",
  "git_branch",
  "git_state",
  "git_status",
  "time",
  "cmd_duration",
  "line_break",
  "character"
]

[time]
disabled = false
format = "🕙 [%T]"

[kubernetes]
symbol = "⛵ "
style = "dim green"
disabled = false
